### ISSUE TITLE
Home Page - Setup Files

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/foundations-group-project-autumn-poison#1]
# Story
As a developer I'll need boilerplate files to start with

# AC
**WHEN** the site is opened up on the server
**THEN** you should see the correct html, css, js printed on the page and in the console log

# Dev Notes
* touch index.html, main.css, and main.js files with boilerplate code
* add Home <h1> tag to index.html
* link main.css, main.js, and bootstrap to html file
* create PrintToDom function and place at the top of the main.js file:
```

**Comment by John-Ryan-Johnson** [comment]
create images folder for .jpeg files
