### ISSUE TITLE
Home Page - Banner Photo

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/foundations-group-project-autumn-poison#10]
# User Story
As a user, when I pull up the home page, I'd like to see a banner photo of the band at the top of the page

# AC
**WHEN** I load the home page
**THEN** I should see a banner band photo at the top of the page
**AND** It should be centered at the top of the page

# Dev Notes
* Create banner photo div using empty div
* Center banner photo at the top of the page
* create js for loop function to randomize photo displayed

**Comment by jacob-bw** [comment]
![Autumn Poison - Home](https://user-images.githubusercontent.com/51467735/65004527-51d9e400-d8c2-11e9-909c-6ede1549e00d.PNG)

**Comment by John-Ryan-Johnson** [comment]
add printToDom function to main.js

const printToDOM = (divID, textToPrint) => {
    document.getElementById(divID).innerHTML = textToPrint;
}

**Comment by phillipsja97** [comment]
👍
