### ISSUE TITLE
Events Page - Concert Cards

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/foundations-group-project-autumn-poison#15]
# User Story
As a user, when I visit the Events page, when I click on a city and date, a concert card should expand with more details about the show and an option to buy a ticket

# AC
**WHEN**  I click on a tour date
**THEN** a concert card should pop up with more details about the show and an option to buy a ticket

# Dev Notes
* add eventlistener to listen for the city that is clicked in the array by class
* in main.js create printToDom function that prints card, and the card div in the printToDom function will include the show details from the concert array
* card should have "buy" button that is centered at the bottom of the card and directs to purchase.html when clicked.
* use bootstrap card

**Comment by jacob-bw** [comment]
https://getbootstrap.com/docs/4.3/components/card/#example

```
<div class="card" style="width: 18rem;">
  <img src="..." class="card-img-top" alt="...">
  <div class="card-body">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="btn btn-primary">Go somewhere</a>
  </div>
</div>
```
