### ISSUE TITLE
Events Page - Buy Button

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/foundations-group-project-autumn-poison#17]
# User Story
As a user when I click the Buy button on the Concert Card, I want to be redirected to a page where I can purchase the concert ticket.

# AC
**WHEN** I click the Buy button on the concert card
**THEN** I will be redirected to the purchase.html page where I can purchase a concert ticket

# Dev Notes
* add an event listener to Buy button on product card, that will take the user to the purchase.html page where they can purchase the selected ticket

**Comment by jacob-bw** [comment]
Uses the same buy button event listener function as on "merch" page - leading to purchase.html

```
const buyButton = document.getElementById('buy').addEventListener('click', () => {                                document.location.href="./purchase.html" });
```
