### ISSUE TITLE
Home Page - Wireframe/Mockups

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/foundations-group-project-autumn-poison#2]
# Story
As a developer, you'll need to create a Moqup with the wireframe of the page you'll be building.

# AC
**WHEN** you create the Moqup
**THEN** you'll include a navbar with the Home, Events, Merch, and Discography buttons.
**AND** You'll have divs for the Band Picture, and about section, and a rolling Carousel of live band photos 

# Dev Notes
* create moqup and add to ticket before completing

**Comment by jacob-bw** [comment]
![Autumn Poison - Home](https://user-images.githubusercontent.com/51467735/64912280-8434e700-d6f2-11e9-9c2d-d2cc03368a55.PNG)
