### ISSUE TITLE
Discography - Print Discography Cards Function

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/foundations-group-project-autumn-poison#27]
# User Story
As a user, when I pull up the discography page, I'd like to see printed cards of each of the band's albums, along with the corresponding album details, and an option to buy.

# AC
**WHEN** the Discography page loads
**THEN** the user will see printed album cards of the band's discography
**AND** They should be able to click the buy button on each card that will take them to checkout if they'd like to buy that particular album.

# Dev Notes
* create disc.html
* Add Discography h1 tag
* copy Navbar div from index.html
* Create placeholder div in discography.html to print the Discography Cards to:
```
<div id="disc-cards-div"></div>
```
* Define albums array in main.js, that will be later used to print to disc.html: const albums =  []
* In main.js after you've declared your PrintToDom function you will create and call your discCardPrinter function that will build the Discography cards and print them to the DOM

**Comment by phillipsja97** [comment]
👍
