### ISSUE TITLE
Discography - Wireframe

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/foundations-group-project-autumn-poison#29]
# Story
As a developer, you'll need to create a Moqup with the wireframe of the page you'll be building.

# AC
**WHEN** you create the Moqup of the Discography page
**THEN** you'll include a navbar with the Home, Events, Merch, and Discography buttons.
**AND** You'll have Discography Cards printed in a div. Each card will have centered content displaying the album art, album title, list of songs, as well as a Buy button that will allow you to purchase the selected album on the purchase.html page.

# Dev Notes
* create moqup and add to ticket before completing which must include:
 - navbar
 - discography cards displaying the album art, title, and 
    song list
 - buy buttons on each discography/album card

**Comment by ghost** [comment]
![Image from iOS](https://user-images.githubusercontent.com/54124397/64988864-fdb70b80-d891-11e9-89fb-e2b93c9d02ad.jpg)

**Comment by John-Ryan-Johnson** [comment]
Changed buy to purchase.
