### ISSUE TITLE
Merch - HTML

### ISSUE THREAD

**Issue by ghost** [nss-evening-cohort-10/foundations-group-project-autumn-poison#5]
# User Story
As a user, I should see a page with all available band merch for purchase, and details of the merch, including prices.

AC
**WHEN** I pull up the merch page
**THEN** I should see a list of all available merch for purchase

Dev Notes
* Create merch.html file
* add the NavBar copied over from the Home Page. Remember to change the active class.
* add Band Merch h1 tag
* create div placeholders for sort buttons & product card

**Comment by phillipsja97** [comment]
![image](https://user-images.githubusercontent.com/51938283/64912283-8c8d2200-d6f2-11e9-9f26-1e2301d0afb5.png)
